spring:
  datasource:
    url: jdbc:postgresql://localhost:7432/blog
    username: postgres
    password: postgres
  session:
    jdbc:
      cleanup-cron: 0 0 1 * * *
      table-name: user_session
      initialize-schema: always
  security:
    remember-me:
      key: ${RM_KEY:my-secure-key}

  devtools:
    livereload:
      port: 35730

server:
  port: 8081
