name: Admin-Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:latest
        ports:
          - 7432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set execute permission for gradlew
        working-directory: admin-backend
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: admin-backend
        run: ./gradlew build

      - name: Run Integration Tests
        working-directory: admin-backend
        run: ./gradlew test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Testergebnisse
          path: build/reports/tests/test
